# Generated by Django 4.2.6 on 2023-10-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='subtasks',
        ),
        migrations.AddField(
            model_name='contact',
            name='first_name',
            field=models.CharField(default='default_value', max_length=30),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default='default_value', max_length=30),
        ),
        migrations.AddField(
            model_name='subtask',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
