# Generated by Django 4.2.6 on 2023-10-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_contact_full_name_remove_subtask_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subtask',
        ),
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.JSONField(default=list),
        ),
    ]
